// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Fallback values en cas de problème avec les variables d'environnement
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || 'https://btujycztangypsraqfdw.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0dWp5Y3p0YW5neXBzcmFxZmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc0NDAwMTQsImV4cCI6MjA4MzAxNjAxNH0.BLijGioY1oBzbFcmXjKvl-enKppyZfmzwcEVxnINq5w';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Client sans typage strict pour supporter les nouvelles tables
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});